project:
  type: book
  output-dir: docs

format:
  html:
    link-external-newwindow: true
    cover-image: cover.png
    theme: 
      light: 
        - cosmo
      #   - css/fira-code.css
      #   - css/light.css
      # dark:
      #   - slate
      #   - css/dark.css
    lang: "fr"
    code-link: true
    code-overflow: wrap
    toc: true
    # monofont: Fira Code
    # number-depth: 2
  pdf:
    documentclass: scrreprt

book:
  # reader-mode: true
  # page-navigation: true
  title: "Fichiers NetCDF"
  subtitle: "Exemple tiré de la NOAA"
  author: 
    - name: "Alain CORVISIER"
      email: alain.corvisier@proton.me
  date: today
  sidebar: 
    style: floating
  repo-url: https://github.com/a-lambda/sst/
  repo-actions: [edit]
  search: true
  chapters:
    - index.qmd
    - intro.qmd
    - href: SST_001_recuperation_donnees.qmd
      text: Données SST
    - href: SST_02_timeseries.qmd
      text: Données temporelles
    - href: SST_03_levelplot.qmd
      text: Un fichier SST
    - references.qmd

bibliography: references.bib

